# Site
name: "NombreParaMascota"
title: "NombreParaMascota"
description: "Es el lugar ideal para encontrar el nombre perfecto para tu compañero peludo, escamoso o emplumado. Ya sea que tengas un perro, gato, pez, ave, conejo o cualquier otra mascota, aquí descubrirás miles de ideas originales, significativas y divertidas para nombrarla. Además, te ofrecemos consejos, significados, tendencias y listas temáticas que harán que elegir un nombre sea una experiencia única y especial."
logo: 'assets/images/logo-nombre-para-mascota-footprint.jpg'
favicon: 'assets/images/logo-nombre-para-mascota-footprint.jpg'
baseurl: /
google_analytics: 'G-0FQ6L9J3YM'
google_ads: 'ca-pub-5463145385158070'
disqus: 'nombreparamascota'
mailchimp-list: false
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  admin:
    name: Admin
    display_name: Admin
    avatar: 'assets/images/logo-nombre-para-mascota-footprint.jpg'
    email: wowthemesnet@gmail.com
    web: https://nombreparamascota.com
    twitter: https://nombreparamascota.com
    description: "Autor nombreparamascota.com"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
